apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client-tls
spec:
  secretName: client-tls
  issuerRef:
    name: signer
    kind: ClusterIssuer
  commonName: client
  subject:
    countries:
      - US
    organizationalUnits:
      - RedHat
  usages:
    - client auth
  dnsNames:
  - client
  - client.client.svc
  - client.client.svc.cluster.local
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: client-tls
        key: keystorePassword