apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: client-ui
spec:
  hosts:
  - "client-ui.apps.example.com"
  gateways:
  - client-ui
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 3001
        host: client